ENV_CONFIG=dev
ENVIRONMENT=dev
AZURE_SUBSCRIPTION="Digital Screening DToS - Core Services Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=DTOSS-8589-shared-config
ENABLE_SOFT_DELETE=false
