# Generated by Django 5.1.7 on 2025-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinic_created_at_alter_clinicslot_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='risk_type',
            field=models.CharField(choices=[('MIXED_RISK', 'Mixed risk'), ('ROUTINE_RISK', 'Routine risk'), ('MOBILE', 'Mobile screening')], default='MIXED_RISK', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='type',
            field=models.CharField(choices=[('ASSESSMENT', 'Assessment'), ('SCREENING', 'Screening')], max_length=50),
        ),
    ]
