# Generated by Django 5.1.8 on 2025-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reinvite',
            field=models.BooleanField(default=False),
        ),
    ]
