# Generated by Django 5.2.1 on 2025-05-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_alter_appointment_status'),
        ('clinics', '0008_appointment_stopped_reasons'),
    ]

    operations = [
    ]
