# Generated by Django 5.2.1 on 2025-05-28 15:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0009_merge_20250514_1140"),
    ]

    operations = [
        migrations.RunSQL(
            [
                "TRUNCATE TABLE clinics_provider CASCADE",
                "TRUNCATE TABLE clinics_screeningepisode CASCADE",
            ]
        ),
        migrations.RemoveField(
            model_name="provider",
            name="id",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="id",
        ),
        migrations.RemoveField(
            model_name="setting",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="id",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="setting",
        ),
        migrations.RemoveField(
            model_name="clinicslot",
            name="id",
        ),
        migrations.RemoveField(
            model_name="clinicslot",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="screeningepisode",
            name="id",
        ),
        migrations.RemoveField(
            model_name="screeningepisode",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="clinic_slot",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="screening_episode",
        ),
        migrations.AddField(
            model_name="provider",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="provider",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.provider",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="setting",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.setting",
            ),
        ),
        migrations.AddField(
            model_name="clinicslot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="clinicslot",
            name="clinic",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.clinic",
                related_name="clinic_slots",
            ),
        ),
        migrations.AddField(
            model_name="screeningepisode",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="screeningepisode",
            name="participant",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="participants.participant"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="screening_episode",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.screeningepisode",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="clinic_slot",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="clinics.clinicslot",
            ),
        ),
    ]
