# Generated by Django 5.1.8 on 2025-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.TextField()),
                ('nhs_number', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('ethnicity', models.TextField()),
                ('address', models.TextField()),
                ('risk_level', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
