# Generated by Django 5.1.8 on 2025-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='extra_needs',
            field=models.JSONField(default=[]),
        ),
    ]
