# Generated by Django 5.1.8 on 2025-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_extra_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='extra_needs',
            field=models.JSONField(default=list),
        ),
    ]
