# Generated by Django 5.1.8 on 2025-05-14 09:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_extra_needs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='address',
        ),
        migrations.AlterField(
            model_name='participant',
            name='ethnicity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='extra_needs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ParticipantAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=5)),
                ('postcode', models.CharField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='participants.participant')),
            ],
        ),
    ]
