# Generated by Django 5.1.8 on 2025-05-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_remove_participant_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantaddress',
            old_name='street',
            new_name='lines',
        ),
    ]
