# Generated by Django 5.2.1 on 2025-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_rename_street_participantaddress_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='ethnicity',
        ),
        migrations.AddField(
            model_name='participant',
            name='ethnic_group',
            field=models.CharField(blank=True, choices=[('English, Welsh, Scottish, Northern Irish or British', 'English, Welsh, Scottish, Northern Irish or British'), ('Irish', 'Irish'), ('Gypsy or Irish Traveller', 'Gypsy or Irish Traveller'), ('Any other White background', 'Any other White background'), ('White and Black Caribbean', 'White and Black Caribbean'), ('White and Black African', 'White and Black African'), ('White and Asian', 'White and Asian'), ('Any other mixed or multiple ethnic background', 'Any other mixed or multiple ethnic background'), ('Indian', 'Indian'), ('Pakistani', 'Pakistani'), ('Bangladeshi', 'Bangladeshi'), ('Chinese', 'Chinese'), ('Any other Asian background', 'Any other Asian background'), ('African', 'African'), ('Caribbean', 'Caribbean'), ('Any other Black, African or Caribbean background', 'Any other Black, African or Caribbean background'), ('Arab', 'Arab'), ('Any other ethnic group', 'Any other ethnic group'), ('Prefer not to say', 'Prefer not to say')], null=True),
        ),
    ]
