# Generated by Django 5.2.1 on 2025-05-28 15:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_remove_participant_ethnicity_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            [
                "TRUNCATE TABLE participants_participant CASCADE",
            ]
        ),
        migrations.RemoveField(
            model_name="participant",
            name="id",
        ),
        migrations.AddField(
            model_name="participant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
