# Generated by Django 5.2.1 on 2025-05-29 13:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_switch_primary_keys_to_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantaddress",
            name="id",
        ),
        migrations.AddField(
            model_name="participantaddress",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
